[project]
name = "pipeline"
version = "0.1.0"
requires-python = "==3.11.*"
description = "Run testing models"

dependencies = [
  "numpy",
  #"torch>=1.13",
  "scikit-learn>=1.1",
  "datasets>=2.9",
  "tqdm>=4.64",
  "enformer-pytorch>=0.5",
  "transformers",
  #"flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.0.post2/flash_attn-2.8.0.post2+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl",
  "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl",
  "mamba-ssm @ https://github.com/state-spaces/mamba/releases/download/v2.2.5/mamba_ssm-2.2.5+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl",
  "causal-conv1d @ https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.5.2/causal_conv1d-1.5.2+cu12torch2.7cxx11abiFALSE-cp311-cp311-linux_x86_64.whl",

  # В Dockerfile они ставились отдельно
  "einops",
  "optree",
  "regex",
  "omegaconf",
  "torch==2.7.1",
 #"ai2-olmo",
 # "triton",
  "wandb",
  "hf_xet",
  "ai2-olmo>=0.6.0",
  "kipoiseq",
  "pytabix",
  "pyBigWig",
  "joblib"
  #"selene-sdk"
  #"mamba-ssm",
  #"causal-conv1d>=1.4.0"
]

[project.scripts]
pipeline = "main:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages   = ["pipeline", "extractors", "data_dir"]
py-modules = ["main"]


#[tool.uv.dependency-groups]
#dev = [
#  "jupyterlab",
#  "ipykernel",
#]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }

[tool.uv]
build-constraint-dependencies = ["setuptools>=60", "wheel", "ninja", "packaging"]








#[tool.uv.sources]
#torch = {index="pytorch-cu118"}

#[tool.uv]
#override-dependencies = ["torch==2.5.1+cu118"]
#no-build-isolation-package = ["mamba-ssm", "causal-conv1d"]

#[tool.uv.extra-build-variables]
#mamba-ssm = {MAMBA_FORCE_BUILD = "TRUE"}
#causal-conv1d = {CAUSAL_CONV1D_FORCE_BUILD = "TRUE"}


#[[tool.uv.index]]
#name="pytorch-cu118"
#url = "https://download.pytorch.org/whl/cu118"
#explicit=true

#[tool.uv.pip]
#torch-backend = "cu126"

#[tool.uv]
#no-build-isolation-package = ['mamba-ssm', "causal-conv1d"]
