[project]
name = "enformer-pipeline"
version = "0.1.0"
requires-python = ">=3.11"
description = "PyTorch Enformer embedding + logreg cls pipeline"


dependencies = [
  "numpy>=2.3.1",
  "torch>=1.13",
  "scikit-learn>=1.1",
  "datasets>=2.9",
  "tqdm>=4.64",
  "enformer-pytorch @ git+https://github.com/lucidrains/enformer-pytorch.git@main#egg=enformer-pytorch"
]


[project.scripts]
pipeline = "run_enformer:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
